#server:
#  port: 8080
#
#eureka:
#  instance:
#   hostname: localhost
#
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: user-client
#          uri: http://localhost:8090/
#          predicates:
#            - Path=/api

server:
  port: 8080

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  mvc:
    dispatch-options-request: true
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application.name: api
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
          add-to-simple-url-handler-mapping: true
          cors-configurations: 
            '[/**]':
              allowed-origins: "*"
              allowed-methods: "*"
              allowed-headers: "*"
      discovery.locator.enabled: true
      routes:
        - id: user-client
          uri: lb://USER-CLIENT
          predicates:
            Path=/api/**
        - id: wish-client
          uri: lb://WISH-CLIENT
          predicates:
            Path=/wish/**


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      